//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIVERSIDAD.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class Matricula
    {
        public int idMatricula { get; set; }
        public int idEstudiante { get; set; }
        public int NumeroCreditos { get; set; }
        public int ValorCredito { get; set; }
        public int TotalMatricula { get; set; }
        public System.DateTime FechaMatricula { get; set; }
        public string SemestreMatricula { get; set; }
        public string MateriasMatriculadas { get; set; }

        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
    }
}
